### ISSUE TITLE
config.json is a symlink

### ISSUE THREAD

**Issue by reestr** [z3t0/zwm#23]
.hammerspoon/examples/config.json in the git repo is a symlink and not a file.  Not possible to copy it into the ~/.zwm per the instructions on the readme

**Comment by z3t0** [comment]
Sorry for that! I was using a separate directory for the config as I as eventually hoping to ship the entire thing as one product. 

I'll switch the link for the actual file today.

**Comment by z3t0** [comment]
Note that the file config.json needs to be available at ~/.zwm.json and this repo needs to cloned into ~/.hammerspoon
